// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANInEBqc2H3sSIMsJv678v9k9LYVESZGI',
    appId: '1:520694391981:web:55e5bd6cd36d3412335224',
    messagingSenderId: '520694391981',
    projectId: 'projecttest-9ac34',
    authDomain: 'projecttest-9ac34.firebaseapp.com',
    storageBucket: 'projecttest-9ac34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuMwwe_xWJRzGevyeeG5rDL67gs-HABo',
    appId: '1:520694391981:android:ffa7f79330b8cb8a335224',
    messagingSenderId: '520694391981',
    projectId: 'projecttest-9ac34',
    storageBucket: 'projecttest-9ac34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdb1JtX9jf000MCBteGmLAEZmzCY0qB88',
    appId: '1:520694391981:ios:6c0b3df57c2e9fbb335224',
    messagingSenderId: '520694391981',
    projectId: 'projecttest-9ac34',
    storageBucket: 'projecttest-9ac34.appspot.com',
    iosClientId: '520694391981-mjes274s969vfq4uf61c5la2ijrho57s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdb1JtX9jf000MCBteGmLAEZmzCY0qB88',
    appId: '1:520694391981:ios:6c0b3df57c2e9fbb335224',
    messagingSenderId: '520694391981',
    projectId: 'projecttest-9ac34',
    storageBucket: 'projecttest-9ac34.appspot.com',
    iosClientId: '520694391981-mjes274s969vfq4uf61c5la2ijrho57s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
